os: linux
language: minimal
services:
- docker
# DOCKER_USERNAME/DOCKER_PASSWORD have been configured in Travis CI
# env:
before_install:
- echo "Before install"
before_script:
- docker pull neos/server || true
script:
- docker build --pull --cache-from neos/server --tag neos/server .
- docker volume create neosmap-data
- docker run --rm -v neosmap-data:/var/lib/postgresql/12/main neos/server import
- docker run --rm -v neosmap-data:/var/lib/postgresql/12/main -p 8080:80 -d neos/server run
- sleep 30
- make DOCKER_IMAGE=neos/server stop
after_script:
- docker images
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]];
  then
  docker images ;
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ;
  docker push neos/server ;
  fi
notifications:
  email: true
